# Generated by Django 3.2 on 2021-04-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participant',
            },
        ),
    ]
